# Generated by Django 5.0 on 2023-12-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPaths',
            fields=[
                ('pathID', models.AutoField(primary_key=True, serialize=False)),
                ('pathName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('userType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('pathID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningpaths')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('moduleID', models.AutoField(primary_key=True, serialize=False)),
                ('moduleName', models.CharField(max_length=255)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapterID', models.AutoField(primary_key=True, serialize=False)),
                ('chapterName', models.CharField(max_length=255)),
                ('moduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=255)),
                ('chapterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('notificationType', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='MembersCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='JoinCourseRequests',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatings',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chapters')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='AdminCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
    ]
